const safeParse=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}};
const state={user:safeParse("carelinkUser",null),events:safeParse("carelinkEvents",[]),users:safeParse("carelinkUsers",[]),online:navigator.onLine,lowBandwidth:localStorage.getItem("carelinkLowBandwidth")==="1"};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("carelinkUser",JSON.stringify(state.user));localStorage.setItem("carelinkEvents",JSON.stringify(state.events));localStorage.setItem("carelinkUsers",JSON.stringify(state.users));}
function toast(message){const el=$("toast");if(!el){alert(message);return;}el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600);}
function setNetwork(){state.online=navigator.onLine;if($("networkDot"))$("networkDot").className="dot "+(state.online?"online":"offline");if($("networkText"))$("networkText").textContent=state.online?"Online":"Offline";if($("patientConnection"))$("patientConnection").textContent=state.online?"Good":"Offline";if($("chwSync"))$("chwSync").textContent=state.online?"Synced":"Pending sync";}
function setLowBandwidth(on){state.lowBandwidth=on;document.body.classList.toggle("low-bandwidth",on);localStorage.setItem("carelinkLowBandwidth",on?"1":"0");if($("lowBandwidthBtn"))$("lowBandwidthBtn").textContent=on?"Standard mode":"Low-bandwidth mode";}
function addEvent(title,detail){state.events.unshift({date:new Date().toLocaleString(),title,detail});save();renderTimeline();}
function renderTimeline(){if(!$("timeline"))return;const list=state.events.length?state.events:[{date:"Today · 9:10 AM",title:"Profile created",detail:"CareLink demo account ready."}];$("timeline").innerHTML=list.slice(0,8).map(e=>`<div class="event"><small>${e.date}</small><div><strong>${e.title}</strong><div class="muted">${e.detail}</div></div></div>`).join("");}
function renderQueues(){if($("patientQueue"))$("patientQueue").innerHTML=[["Musa Bello","Fever / headache","Awaiting review"],["Aisha Ibrahim","Antenatal follow-up","Scheduled 11:30 AM"],["John Peter","Blood pressure follow-up","Pending referral"],["Fatima Umar","Child health","Needs doctor review"]].map(x=>`<div class="queue-item"><div><strong>${x[0]}</strong><small>${x[1]}</small></div><span class="pill">${x[2]}</span></div>`).join("");if($("doctorQueue"))$("doctorQueue").innerHTML=[["Aisha Ibrahim","Antenatal follow-up","Priority"],["John Peter","BP follow-up","Routine"],["Fatima Umar","Child health","Priority"],["Musa Bello","Fever / headache","Routine"]].map(x=>`<div class="queue-item"><div><strong>${x[0]}</strong><small>${x[1]}</small></div><span class="pill">${x[2]}</span></div>`).join("");}
function showDashboard(){$("loginView").classList.remove("active");$("dashboardView").classList.add("active");$("welcomeTitle").textContent=`Welcome, ${state.user.name}`;$("roleSubtitle").textContent={patient:"Patient portal · Book care and track your follow-ups.",chw:"Community health worker portal · Capture and coordinate rural cases.",doctor:"Doctor portal · Review remote consultation requests."}[state.user.role]||"CareLink portal";["patient","chw","doctor"].forEach(r=>$(r+"Dashboard").classList.toggle("hidden",state.user.role!==r));renderTimeline();renderQueues();}
function showAuth(mode){const signIn=mode==="signin";$("signInForm").classList.toggle("hidden",!signIn);$("signUpForm").classList.toggle("hidden",signIn);$("signInTab").classList.toggle("active",signIn);$("signUpTab").classList.toggle("active",!signIn);}
function logout(){state.user=null;save();$("dashboardView").classList.remove("active");$("loginView").classList.add("active");showAuth("signin");}
function init(){
  $("signInTab").addEventListener("click",()=>showAuth("signin"));
  $("signUpTab").addEventListener("click",()=>showAuth("signup"));
  $("signInForm").addEventListener("submit",e=>{e.preventDefault();const email=$("signInEmail").value.trim().toLowerCase(),password=$("signInPassword").value;const user=state.users.find(u=>u.email===email&&u.password===password);if(!user){toast("Incorrect email or password. Please sign up first.");return;}state.user={name:user.name,email:user.email,phone:user.phone,age:user.age,role:user.role};state.events=[];save();showDashboard();toast("Signed in successfully.");});
  $("signUpForm").addEventListener("submit",e=>{e.preventDefault();const name=$("signUpName").value.trim(),email=$("signUpEmail").value.trim().toLowerCase(),phone=$("signUpPhone").value.trim(),age=Number($("signUpAge").value),role=$("signUpRole").value,password=$("signUpPassword").value,confirm=$("signUpConfirmPassword").value;if(!name||!email||!phone||!age||!role||!password||!confirm){toast("Please complete all fields.");return;}if(!/^\S+@\S+\.\S+$/.test(email)){toast("Please enter a valid email address.");return;}if(password.length<6){toast("Password must be at least 6 characters.");return;}if(password!==confirm){toast("Passwords do not match.");return;}if(age<1||age>120){toast("Please enter a valid age.");return;}if(state.users.some(u=>u.email===email)){toast("An account with this email already exists.");return;}const user={name,email,phone,age,role,password};state.users.push(user);state.user={name,email,phone,age,role};state.events=[];save();e.target.reset();showDashboard();toast("Account created successfully.");});
  $("logoutBtn").addEventListener("click",logout);$("lowBandwidthBtn").addEventListener("click",()=>setLowBandwidth(!state.lowBandwidth));
  $("bookBtn").addEventListener("click",()=>{const service=$("serviceSelect").value,time=$("timeSelect").value;addEvent("Consultation requested",`${service} · ${time}`);toast(state.online?"Consultation request sent.":"Saved offline. It will sync when connected.");});
  $("checkinBtn").addEventListener("click",()=>{const text=$("symptomInput").value.trim();if(!text)return toast("Please enter a short check-in.");addEvent("Check-in saved",text);$("symptomInput").value="";toast(state.online?"Check-in saved for review.":"Check-in saved offline.");});
  $("syncBtn").addEventListener("click",()=>toast(state.online?"Local records synchronized.":"Still offline — nothing was uploaded."));$("addPatientBtn").addEventListener("click",()=>toast("Demo registration form opened. Add a real database in Phase 2."));window.addEventListener("online",setNetwork);window.addEventListener("offline",setNetwork);setNetwork();setLowBandwidth(state.lowBandwidth);if(state.user)showDashboard();else showAuth("signin");
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
