(function(){
'use strict';
const $ = id => document.getElementById(id);
function getJSON(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback;}catch(e){return fallback;}}
const state={user:getJSON('carelinkUser',null),users:getJSON('carelinkUsers',[]),events:getJSON('carelinkEvents',[]),online:navigator.onLine,lowBandwidth:localStorage.getItem('carelinkLowBandwidth')==='1'};
if(!Array.isArray(state.users)) state.users=[];
if(!Array.isArray(state.events)) state.events=[];
function save(){localStorage.setItem('carelinkUser',JSON.stringify(state.user));localStorage.setItem('carelinkUsers',JSON.stringify(state.users));localStorage.setItem('carelinkEvents',JSON.stringify(state.events));}
function toast(msg){const el=$('toast');if(!el){alert(msg);return;}el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600);}
function showAuth(mode){const signin=mode==='signin';$('signInForm').classList.toggle('hidden',!signin);$('signUpForm').classList.toggle('hidden',signin);$('signInTab').classList.toggle('active',signin);$('signUpTab').classList.toggle('active',!signin);}
function showDashboard(){ $('loginView').classList.remove('active');$('dashboardView').classList.add('active'); $('welcomeTitle').textContent='Welcome, '+state.user.name; $('roleSubtitle').textContent={patient:'Patient portal · Book care and track your follow-ups.',chw:'Community health worker portal · Capture and coordinate rural cases.',doctor:'Doctor portal · Review remote consultation requests.'}[state.user.role]||'CareLink portal'; ['patient','chw','doctor'].forEach(r=>{const el=$(r+'Dashboard');if(el)el.classList.toggle('hidden',state.user.role!==r);}); renderTimeline();renderQueues();}
function logout(){state.user=null;save();$('dashboardView').classList.remove('active');$('loginView').classList.add('active');showAuth('signin');}
function renderTimeline(){const el=$('timeline');if(!el)return;const list=state.events.length?state.events:[{date:'Today · 9:10 AM',title:'Profile created',detail:'CareLink account ready.'}];el.innerHTML=list.slice(0,8).map(e=>'<div class="event"><small>'+e.date+'</small><div><strong>'+e.title+'</strong><div class="muted">'+e.detail+'</div></div></div>').join('');}
function renderQueues(){const p=$('patientQueue'),d=$('doctorQueue');const rows=[['Musa Bello','Fever / headache','Awaiting review'],['Aisha Ibrahim','Antenatal follow-up','Scheduled 11:30 AM'],['John Peter','Blood pressure follow-up','Pending referral'],['Fatima Umar','Child health','Needs doctor review']];if(p)p.innerHTML=rows.map(x=>'<div class="queue-item"><div><strong>'+x[0]+'</strong><small>'+x[1]+'</small></div><span class="pill">'+x[2]+'</span></div>').join('');if(d)d.innerHTML=rows.map(x=>'<div class="queue-item"><div><strong>'+x[0]+'</strong><small>'+x[1]+'</small></div><span class="pill">'+x[2]+'</span></div>').join('');}
function buildTimeSlots(startHour,endHour,stepMinutes){const slots=[];for(let t=startHour*60;t<=endHour*60;t+=stepMinutes){const h24=Math.floor(t/60),m=t%60,period=h24>=12?'PM':'AM',h12=h24%12===0?12:h24%12;slots.push((h12+':'+(m<10?'0'+m:m)+' '+period));}return slots;}
function populateBookingFields(){const timeSelect=$('timeSelect'),dateSelect=$('dateSelect');if(timeSelect){timeSelect.innerHTML=buildTimeSlots(10,16,30).map(t=>'<option>'+t+'</option>').join('');}if(dateSelect){const now=new Date(),iso=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);dateSelect.min=iso;if(!dateSelect.value)dateSelect.value=iso;}}
function setNetwork(){state.online=navigator.onLine;const dot=$('networkDot'),txt=$('networkText'),pc=$('patientConnection'),cs=$('chwSync');if(dot)dot.className='dot '+(state.online?'online':'offline');if(txt)txt.textContent=state.online?'Online':'Offline';if(pc)pc.textContent=state.online?'Good':'Offline';if(cs)cs.textContent=state.online?'Synced':'Pending sync';}
function init(){
 const signInTab=$('signInTab'),signUpTab=$('signUpTab'),signInForm=$('signInForm'),signUpForm=$('signUpForm');
 signInTab.onclick=()=>showAuth('signin'); signUpTab.onclick=()=>showAuth('signup');
 signInForm.onsubmit=function(e){e.preventDefault();const email=$('signInEmail').value.trim().toLowerCase(),password=$('signInPassword').value;const user=state.users.find(u=>u.email===email&&u.password===password);if(!user){toast('Incorrect email or password. Please sign up first.');return false;}state.user={name:user.name,email:user.email,phone:user.phone,age:user.age,role:user.role};state.events=[];save();showDashboard();toast('Signed in successfully.');return false;};
 signUpForm.onsubmit=function(e){e.preventDefault();const name=$('signUpName').value.trim(),email=$('signUpEmail').value.trim().toLowerCase(),phone=$('signUpPhone').value.trim(),age=Number($('signUpAge').value),role=$('signUpRole').value,password=$('signUpPassword').value,confirm=$('signUpConfirmPassword').value;if(!name||!email||!phone||!age||!role||!password||!confirm)return toast('Please complete all fields.');if(!/^\S+@\S+\.\S+$/.test(email))return toast('Please enter a valid email address.');if(age<1||age>120)return toast('Please enter a valid age.');if(password.length<6)return toast('Password must be at least 6 characters.');if(password!==confirm)return toast('Passwords do not match.');if(state.users.some(u=>u.email===email))return toast('An account with this email already exists.');const user={name,email,phone,age,role,password};state.users.push(user);state.user={name,email,phone,age,role};state.events=[];save();signUpForm.reset();showDashboard();toast('Account created successfully.');return false;};
 $('logoutBtn').onclick=logout;$('lowBandwidthBtn').onclick=()=>{state.lowBandwidth=!state.lowBandwidth;document.body.classList.toggle('low-bandwidth',state.lowBandwidth);localStorage.setItem('carelinkLowBandwidth',state.lowBandwidth?'1':'0');$('lowBandwidthBtn').textContent=state.lowBandwidth?'Standard mode':'Low-bandwidth mode';};
 $('bookBtn').onclick=()=>{const time=$('timeSelect')?$('timeSelect').value:'',date=$('dateSelect')?$('dateSelect').value:'';toast(date&&time?'Consultation requested for '+date+' at '+time+'.':'Consultation request saved.');};$('checkinBtn').onclick=()=>toast('Check-in saved.');$('syncBtn').onclick=()=>toast(state.online?'Local records synchronized.':'Still offline — nothing was uploaded.');$('addPatientBtn').onclick=()=>toast('Registration form opened.');
 populateBookingFields();
 window.addEventListener('online',setNetwork);window.addEventListener('offline',setNetwork);setNetwork();document.body.classList.toggle('low-bandwidth',state.lowBandwidth);if($('lowBandwidthBtn'))$('lowBandwidthBtn').textContent=state.lowBandwidth?'Standard mode':'Low-bandwidth mode';if(state.user&&state.user.name)showDashboard();else showAuth('signin');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
